import type { NextPage } from "next";
import Head from "next/head";
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className="bg-gradient-to-t from-black to-transparent h-screen" >
      <div className="-z-30 absolute w-full h-screen">
      <Image 
      src = "/barbertools.png"
      layout = "fill"
      objectFit="cover"       
      />
      </div>
      <Head>
        <title>Home | Razor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=" fixed top-0 w-full z-30 ">
        <div className=" lg:h-[80px] bg-[#000] m-auto w-full transition-all duration-[1s] ease-out scale-1">
            <nav className=" flex  text-[#b1af72]   p-4 pt-6 lg:w-[60%] m-auto ">
              <div className="text-xl cursor-pointer hover:text-[#c4c173] ">RAZOR</div>

              <div className=" text-white  justify-center w-full hidden sm:flex z-40">
                <a className="px-2 text-[#f2f2f2] hover:text-amber-100 font-thin" href="#">Home</a>
                <a className="px-2 text-[#f2f2f2] hover:text-amber-100 font-thin" href="#">Services</a>
                <a className="px-2 text-[#f2f2f2] hover:text-amber-100 font-thin" href="#">About</a>
                <a className="px-2 text-[#f2f2f2] hover:text-amber-100 font-thin" href="#">Book</a>

              </div>
              
              <div className=" lg:hidden sm:hidden w-full flex relative">
                <button  className="flex flex-col float-right absolute right-0">
                  <div className="w-6 h-[2px] my-[2px] bg-[#b1af72]"></div>
                  <div className="w-6 h-[2px] my-[2px] bg-[#b1af72]"></div>
                  <div className="w-6 h-[2px] my-[2px] bg-[#b1af72]"></div>
                </button>

               
              </div>

              

              
              <div className="block lg:flex lg:items-center w-auto">
                <ul className="hidden">
                <li><a href="#" className="lg:block-inline hover:text-green-500">Link</a></li>
                <li><a href="#" className="lg:block-inline hover:text-green-500">Link</a></li>
                <li><a href="#" className="lg:block-inline hover:text-green-500">Link</a></li>
                <li><a href="#" className="lg:block-inline hover:text-green-500">Login</a></li>
                </ul>
              </div>
            </nav>
        </div>
      </header>
     
      <main className="float-left w-full">
        <h2 className=" sm:text-7xl text-6xl text-[#b1af72] text-center  pt-60 pb-10 drop-shadow-sm">RAZOR</h2>
        <h3 className="text-gray-500 text-sm md:pb-20 pb-10 text-center z-0">YOUR JOURNEY BEGINS HERE</h3>
        <div className="flex justify-center">
          
        </div>

        <div className="m-auto lg:w-[60%] md:w-[80%] sm:w[90%]">
          <div className=" text-slate-200 font-thin text-lg justify-center flex w-full">
            <p className="lg:pb-10 sm:pb-10 md:py-10 p-4 z-10  lg:w-[500px] md:w-[500px] mg:text-md float-left lg:text-lg lg:ml-[100px] text-sm">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
            </p>
          </div>
            <div className="flex w-full justify-center">
            <button className=" bg-gradient-to-bl from-[#b1af72] to-[#725a17] lg:mt-10 z-30 cursor-pointer 
            hover:to-[#fff] p-1 px-2 m-4 rounded-sm text-black float-left">Book Now</button>
            </div>
            
        </div>

        <div className="flex w-full flex-wrap justify-left pt-10">
          <div className="w-full sm:basis-1/3 bg-gradient-to-b from-black to-[#090909] rounded-sm border 
          border-[#212121] h-80">
            <h2 className="text-center text-lg text-gray-200 font-thin border-b border-black m-4">Feature 01</h2>
          </div>
          <div className="w-full sm:basis-1/3 bg-gradient-to-b from-black to-[#090909] rounded-sm border 
          border-[#212121] h-80">
            <h2 className="text-center text-lg text-gray-200 font-thin border-b border-black  m-4">Feature 02</h2>
          </div>
          <div className="w-full sm:basis-1/3 bg-gradient-to-b from-black to-[#090909] rounded-sm border 
          border-[#212121] h-80">
            <h2 className="text-center text-lg text-gray-200 font-thin border-b border-black m-4">Feature 03</h2>
          </div>
        </div>
        
       <div className="h-80"></div>
        

        <div className="flex w-full flex-wrap justify-left">
          <div className="w-full sm:basis-1/3 bg-gradient-to-b from-black to-[#090909] rounded-sm border 
          border-[#212121] h-80">
            <h2 className="text-center text-lg text-gray-200 font-thin border-b border-black m-4">Feature 04</h2>
          </div>
          <div className="w-full sm:basis-1/3 bg-gradient-to-b from-black to-[#090909] rounded-sm border 
          border-[#212121] h-80">
            <h2 className="text-center text-lg text-gray-200 font-thin border-b border-black  m-4">Feature 05</h2>
          </div>
          <div className="w-full sm:basis-1/3 bg-gradient-to-b from-black to-[#090909] rounded-sm border 
          border-[#212121] h-80">
            <h2 className="text-center text-lg text-gray-200 font-thin border-b border-black m-4">Feature 06</h2>
          </div>
        </div>

  

        <div className="w-full flex relative lg:h-[500px] h-56 pb-10 ">
          <h2 className="  text-[#b1af72] z-10 text-center absolute
           w-full pt-36 text-2xl mg:text-4xl lg:text-4xl lg:pt-80 md:pt-40 font-mono">LEGENDS ARE BORN HERE</h2>
          {/* <Image
          src='/banner.jpg'          
          objectFit="none"
          height={650}
          width={1800}      
          /> */}
        </div>        
      </main>

      <footer className=" bg-[#090909] block float-left pt-10 w-full">
        
        <div className="text-gray-400 py-16 w-40 h-90 border float-left m-6 mb-0 bg-gray-900 text-center lg:w-[600px] lg:h-[300px]" >Map</div>
        <div className="text-white text-sm font-thin float-left mt-8 mr-10 lg:ml-20 lg:text-lg">
          555 Adress St<br/>
          34052 Cityname, State
          <div className="pt-10">Phone Number</div>
          <span className="pt-10">Social Accouns</span>
        </div>
        


        <div className="text-[#ccc] text-center text-xs mt-20 h-10 inline-block w-full font-thin bg-black pt-2">
        Copyright @ 2022 Ross Duris
        </div>
        
      </footer>
    </div>
  );
};

export default Home;
